// grid/add-rows-pinned-row/react/src/components/SportRenderer.tsx
import React from 'react';
import type { ICellRendererParams } from 'ag-grid-community';

interface SportRendererProps extends ICellRendererParams {
  value: string;
}

const sportIconMap: Record<string, string> = {
  Swimming: 'swimming',
  Gymnastics: 'running',
  Cycling: 'biking',
  'Ski Jumping': 'skiing',
};

export const SportRenderer: React.FC<SportRendererProps> = ({
  value,
  valueFormatted,
}) => {
  const getValueToDisplay = () => {
    return valueFormatted || value;
  };

  return (
    <div>
      <i className={`fa-solid fa-person-${sportIconMap[value]}`}></i>
      <span style={{ marginLeft: '5px' }}>{getValueToDisplay()}</span>
    </div>
  );
};

// grid/add-delete-rows-pinned-row/vue/src/components/SportRenderer.vue
<template>
  <div>
    <font-awesome-icon :icon="sportIconMap[params.value]" />
    <span style="margin-left: 5px">{{ getValueToDisplay() }}</span>
  </div>
</template>

<script setup lang="ts">
import type { ICellRendererParams } from 'ag-grid-community';

interface Props {
  params: ICellRendererParams;
}

const props = defineProps<Props>();

const sportIconMap: Record<string, string> = {
  Swimming: 'person-swimming',
  Gymnastics: 'person-running',
  Cycling: 'person-biking',
  'Ski Jumping': 'person-skiing',
};

const getValueToDisplay = () => {
  return props.params.valueFormatted || props.params.value;
};
</script>
