// grid/add-rows-pinned-row/react/src/components/SportRenderer.tsx
import React from 'react';
import type { ICellRendererParams } from 'ag-grid-community';

interface SportRendererProps extends ICellRendererParams {
  value: string;
}

const sportIconMap: Record<string, string> = {
  Swimming: 'swimming',
  Gymnastics: 'running',
  Cycling: 'biking',
  'Ski Jumping': 'skiing',
};

export const SportRenderer: React.FC<SportRendererProps> = ({
  value,
  valueFormatted,
}) => {
  const getValueToDisplay = () => {
    return valueFormatted || value;
  };

  return (
    <div>
      <i className={`fa-solid fa-person-${sportIconMap[value]}`}></i>
      <span style={{ marginLeft: '5px' }}>{getValueToDisplay()}</span>
    </div>
  );
};

// grid/add-rows-pinned-row/angular/src/app/components/sport-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererParams } from 'ag-grid-community';
import { ICellRendererAngularComp } from 'ag-grid-angular';

interface SportRendererParams extends ICellRendererParams {
  value: string;
}

@Component({
  selector: 'app-sport-renderer',
  template: `
    <div>
      <i class="fa-solid fa-person-{{ getIcon() }}"></i>
      <span style="margin-left: 5px;">{{ getValueToDisplay() }}</span>
    </div>
  `,
  standalone: true
})
export class SportRenderer implements ICellRendererAngularComp {
  private params!: SportRendererParams;
  
  private sportIconMap: Record<string, string> = {
    Swimming: 'swimming',
    Gymnastics: 'running',
    Cycling: 'biking',
    'Ski Jumping': 'skiing',
  };

  agInit(params: SportRendererParams): void {
    this.params = params;
  }

  refresh(): boolean {
    return false;
  }

  getIcon(): string {
    return this.sportIconMap[this.params.value] || '';
  }

  getValueToDisplay(): string {
    return this.params.valueFormatted || this.params.value;
  }
}
